### ISSUE TITLE
[Up] Legacy Support

### ISSUE THREAD

**Issue by JDeCamp** [x43x61x69/Issues#3]
App Version: 1.4
OS X Version: 10.9.5

---

 What can you do to help you? Please write down below:

I would love to use UP on my Mac, but I am stuck in 10.9 because it is a production machine and I have legacy programs that I will loose in 10.10.  I would gladly purchase thru the App Store, but don't want to if I can't be supported.
I see that you have made that offer to legacy users and was wondering (hoping) that you would extend to me the same offer, even though I am not a legacy user.

Let me know,
Tx,
Jim

**Comment by x43x61x69** [comment]
Hi @JDeCamp !

First of all, thank you for your support and the sorry for the late reply. I didn't login to GitHub until today.

If you already purchased it, in order to protect your email address, I'd like to ask you to leave a comment here: https://vox.vg/up/ with your email. I'll send you the file that can work on 10.9 as long as you have any version <= 1.4.

As for 10.9 support, I decided to remove it from 1.4 for many reasons. I'd like to support all versions of OS X, as that can increase the user base. But Apple does not like that kind of idea, and made it hard for the developers to do so. If you haven't purchased it yet, it's better not doing so unless you plan to upgrade any time soon. Current code base is impossible to work on both 10.9 and 10.10/10.11, and as an independent developer, I don't have enough resources or time to maintain two versions at the same time.

Best,
Cai
